---
name: async_sidebar_counts
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/498901
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/171405
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/502206
milestone: '17.6'
group: group::project management
type: wip
default_enabled: false
