---
name: batch_load_linked_items
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/512056
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/189332
rollout_issue_url:
milestone: '18.0'
group: group::product planning
type: wip
default_enabled: false
