---
name: cache_autocomplete_sources_issues
feature_issue_url: https://gitlab.com/groups/gitlab-org/-/epics/11777
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/156032
rollout_issue_url:
milestone: '17.2'
group: group::product planning
type: wip
default_enabled: false
