---
name: issues_use_correct_work_item_type_id
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/493976
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/169798
rollout_issue_url:
milestone: '17.6'
group: group::project management
type: wip
default_enabled: false
