---
name: always_set_pipeline_failure_reason
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138390
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434228
milestone: '16.7'
type: development
group: group::pipeline execution
default_enabled: false
