---
name: bulk_import_limit_concurrent_batches
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/136018
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/431561
milestone: '16.7'
type: development
group: group::import and integrate
default_enabled: true
