---
name: cache_control_headers_for_openid_jwks
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138405
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/433360
milestone: '16.7'
type: development
group: group::pipeline security
default_enabled: false