---
name: ci_job_token_groups_allowlist
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142441
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/439611
milestone: '16.9'
type: development
group: group::pipeline security
default_enabled: false