---
name: ci_redirect_component_project
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139254
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434511
milestone: '16.8'
type: development
group: group::pipeline authoring
default_enabled: false
