---
name: ci_stop_unlock_pipelines
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/134967
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/428408
milestone: '16.6'
type: development
group: group::pipeline security
default_enabled: false
