---
name: ci_workflow_auto_cancel_on_new_commit
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139358
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434676
milestone: '16.8'
type: development
group: group::pipeline authoring
default_enabled: true
