---
name: code_tasks
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/135717
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/430962
milestone: '16.6'
type: development
group: group::code creation
default_enabled: false
