---
name: github_import_prioritize_collaborators
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139410
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/439742
milestone: '16.9'
type: development
group: group::import and integrate
default_enabled: false
