---
name: invert_omniauth_args_merging
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/135770
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/430348
milestone: '16.6'
type: development
group: group::authentication
default_enabled: false
