---
name: markdown_rust
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139825
rollout_issue_url:
milestone: '16.8'
type: development
group: group::project management
default_enabled: false
