---
name: mr_request_changes
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/134766
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429557
milestone: '16.6'
type: development
group: group::code review
default_enabled: true
