---
name: only_highlight_discussions_requested
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/135096
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429489
milestone: '16.6'
type: development
group: group::code review
default_enabled: false
