---
name: optimize_routable
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/130842
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/424138
milestone: '16.4'
type: development
group: group::tenant scale
default_enabled: false
