---
name: optimize_where_full_path_in
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/137886
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/432863
milestone: '16.7'
type: development
group: group::tenant scale
default_enabled: false
