---
name: prefix_scim_tokens
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139737
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/435423
milestone: '16.8'
type: development
group: group::authentication
default_enabled: false
