---
name: sms_send_wait_time
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/137850
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/432975
milestone: '16.8'
type: development
group: group::anti-abuse
default_enabled: false
