---
name: use_repository_list_tags_on_graphql
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132716
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/426358
milestone: '16.5'
type: development
group: group::container registry
default_enabled: false
