---
name: use_primary_store_as_default_for_shared_state
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/134483
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429884
milestone: '16.6'
type: development
group: group::scalability
default_enabled: false
