---
name: widget_pipeline_pass_subscription_update
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/132353
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/428633
milestone: '16.6'
type: development
group: group::code review
default_enabled: false
