---
name: batch_route_updates
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/432065
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/139782
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17360
milestone: '16.8'
group: group::tenant scale
type: gitlab_com_derisk
default_enabled: false
