---
name: ci_only_one_persistent_ref_creation
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/493356
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/182565
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/527014
milestone: '17.11'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
