---
name: ci_rate_limit_downstream_pipelines
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/425941
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142869
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17471
milestone: '16.9'
group: group::pipeline authoring
type: gitlab_com_derisk
default_enabled: false
