---
name: enhanced_review_email
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/141187
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/437582
milestone: '16.8'
group: group::code review
type: gitlab_com_derisk
default_enabled: false
