---
name: package_registry_npm_fetch_all_tags
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/436099
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142573
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17455
milestone: '16.9'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
