---
name: run_keyword_instrumentation
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/467245
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/169408
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/500973
milestone: '17.6'
group: group::pipeline authoring
type: gitlab_com_derisk
default_enabled: false
