---
name: track_member_activity
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/461338
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/155559
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/471259
milestone: '17.2'
group: group::utilization
type: gitlab_com_derisk
default_enabled: false
