---
name: vsa_duration_from_db
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/432574
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/142618
rollout_issue_url: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/17476
milestone: '16.9'
group: group::optimize
type: gitlab_com_derisk
default_enabled: false
