---
description: Pipeline with name is created
category: Gitlab::Ci::Pipeline::Chain::Metrics
action: create_pipeline_with_name
extra_properties:
identifiers:
- project
- user
- namespace
product_group: pipeline_execution
milestone: "15.9"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/109549
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate

