description: List container repositories
category: list_repositories
action: container
extra_properties:
identifiers:
product_group: container_registry
milestone: "13.6"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/44926
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
