---
description: View all link on Pipeline Analytics failure rate stat
internal_events: true
action: click_view_all_link_in_pipeline_analytics
identifiers:
- project
- namespace
- user
product_group: runner
milestone: '17.2'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/158957
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
