---
description: Tracks the number of authentication requests to the `POST /code_suggestions/tokens` API endpoint.
category: InternalEventTracking
action: code_suggestions_authenticate
label_description:
property_description:
value_description:
extra_properties:
identifiers:
- user
product_section: dev
product_stage: create
product_group: code_creation
milestone: "16.7"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138848
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
