---
description: Tracks filtering of items by unresolved status.
action: filter_unresolved_status
product_group: platform_insights
milestone: '16.1'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/121259
distributions:
  - ce
  - ee
tiers:
  - free
  - premium
  - ultimate
