---
description: Users can set up a SAML provider to sign in to GitLab
action: group_saml_sso
identifiers:
- user
product_group: authentication
milestone: '15.7'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/170427
distributions:
- ce
tiers:
- free
- premium
- ultimate
