---
name: duo_code_review_multi_file
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/532653
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/188117
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/536005
milestone: '18.0'
group: group::code review
type: beta
default_enabled: true
