---
name: mr_merge_skips_close_issue_authorization
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/471849
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/160914
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/475108
milestone: '17.3'
group: group::project management
type: beta
default_enabled: false
