---
name: revalidate_gpg_fingerprints
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/349505
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/182738
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/534717
milestone: '17.11'
group: group::source code
type: beta
default_enabled: false
