include:
  - local: .gitlab/ci/qa-common/main.gitlab-ci.yml
  - template: Verify/Browser-Performance.gitlab-ci.yml

.bundle-base:
  extends:
    - .qa-cache
    - .ruby-image
  before_script:
    - cd qa && bundle install

review-qa-smoke:
  extends:
    - .use-docker-in-docker
    - .bundle-base
    - .default-retry
    - .rules:qa-smoke
  image: ${REGISTRY_HOST}/${REGISTRY_GROUP}/gitlab-build-images/debian-${DEBIAN_VERSION}-ruby-${RUBY_VERSION}:bundler-${BUNDLER_VERSION}-git-2.36-lfs-2.9-chrome-${CHROME_VERSION}-docker-${DOCKER_VERSION}-gcloud-383-kubectl-1.23
  stage: qa
  needs: [review-deploy]
  variables:
    RSPEC_REPORT_OPTS: --force-color --order random --format documentation --format RspecJunitFormatter --out tmp/rspec-${CI_JOB_ID}.xml
    GITLAB_USERNAME: "root"
    GITLAB_PASSWORD: "${REVIEW_APPS_ROOT_PASSWORD}"
    GITLAB_ADMIN_USERNAME: "root"
    GITLAB_ADMIN_PASSWORD: "${REVIEW_APPS_ROOT_PASSWORD}"
    GITLAB_QA_ADMIN_ACCESS_TOKEN: "${REVIEW_APPS_ROOT_TOKEN}"
    GITHUB_ACCESS_TOKEN: "${QA_GITHUB_ACCESS_TOKEN}"
    COLORIZED_LOGS: "true"
    QA_GENERATE_ALLURE_REPORT: "true"
    QA_CAN_TEST_PRAEFECT: "false"
  script:
    - QA_COMMAND="bundle exec bin/qa Test::Instance::Smoke ${QA_GITLAB_URL} -- ${QA_TESTS} ${RSPEC_REPORT_OPTS}"
    - echo "Running - '${QA_COMMAND}'"
    - eval "$QA_COMMAND"
  after_script:
    - |
      echo "Sentry errors for the current review-app test run can be found via following url:"
      echo "https://new-sentry.gitlab.net/organizations/gitlab/releases/$(echo "${CI_COMMIT_SHA}" | cut -c1-11)/?environment=review&issuesType=all&project=19"
  artifacts:
    paths:
      - qa/tmp
    reports:
      junit: qa/tmp/rspec-*.xml
    expire_in: 7 days
    when: always

browser_performance:
  extends:
    - .default-retry
    - .review:rules:review-performance
  image: ${GITLAB_DEPENDENCY_PROXY_ADDRESS}docker:${DOCKER_VERSION}-git
  services:
    - docker:${DOCKER_VERSION}-dind
  stage: qa
  needs: ["review-deploy"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    URL: environment_url.txt

e2e-test-report:
  extends: .rules:prepare-report
  stage: report
  variables:
    ALLURE_RESULTS_GLOB: "qa/tmp/allure-results"

notify-slack:
  extends:
    - .notify-slack
    - .rules:main-run
  stage: report
  variables:
    QA_RSPEC_XML_FILE_PATTERN: ${CI_PROJECT_DIR}/qa/tmp/rspec-*.xml
    RUN_WITH_BUNDLE: "true"
  when: on_failure

export-test-metrics:
  extends:
    - .export-test-metrics
    - .bundle-base
    - .rules:main-run
  stage: report
  variables:
    QA_METRICS_REPORT_FILE_PATTERN: tmp/test-metrics-*.json
  when: always
