---
name: run_clickhouse_migrations_automatically
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/138661
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/434848
milestone: '16.7'
type: ops
group: group::runner
default_enabled: true
