---
name: workhorse_use_aws_sdk_v2
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/482044
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/164597
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/483000
milestone: '17.4'
group: infrastructure
type: ops
default_enabled: true
