---
table_name: bulk_import_configurations
classes:
- BulkImports::Configuration
feature_categories:
- importers
description: Used to store the configuration details of a bulk import of groups or
  projects
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/42978
milestone: '13.5'
gitlab_schema: gitlab_main_cell
desired_sharding_key:
  organization_id:
    references: organizations
    backfill_via:
      parent:
        foreign_key: bulk_import_id
        table: bulk_imports
        sharding_key: organization_id
        belongs_to: bulk_import
table_size: small
desired_sharding_key_migration_job_name: BackfillBulkImportConfigurationsOrganizationId
