trigger-ai-gateway-tagging:
  stage: release-environments
  image: curlimages/curl:latest
  script:
    - |
      curl -X POST --fail \
        -F "token=${AIGW_PIPELINE_TRIGGER_TOKEN}" \
        -F "ref=main" \
        -F "variables[GITLAB_VERSION]=${CI_COMMIT_TAG}" \
        "https://gitlab.com/api/v4/projects/39903947/trigger/pipeline"
  extends:
    - .release-environments:rules:ai-gateway-tagging
  allow_failure: true
